apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  root-password: cm9vdHBhc3N3b3Jk  # Base64 kodowane "rootpassword"
  user: c3R1ZGVudA==           # Base64 kodowane "student"
  user-password: dXNlcnBhc3N3b3Jk   # Base64 kodowane "userpassword"